### ISSUE TITLE
Easter egg commands

### ISSUE THREAD

**Issue by Eeysirhc** [Eeysirhc/sigmabot#25]
List of easter egg commands to eventually add to sigmabot:
* `.lambo`
* `.yacht`
* `.wen`

What should be the expected response for each?

Dev note: create new `eastereggs.py` file to separate from critical FAQ content

**Comment by doug-benn** [comment]
Hello,

I have raised a pull request with some very basic Easter Eggs Commands, Please let me know more are needed/they need changing

#29 

Hope it helps
   - Doug

**Comment by Eeysirhc** [comment]
https://github.com/Eeysirhc/sigmabot/commit/4218c1112ebb3f1414ec35194272c17996b7f861
