### ISSUE TITLE
Add `.nodelist` command

### ISSUE THREAD

**Issue by Eeysirhc** [Eeysirhc/sigmabot#28]
Expected response: ???

Pending answer from koutelier:
_there is a  link i think
Glasgow drops it all the time
that shows all available nodes_

**Comment by cafebedouin** [comment]
This one will work. I'll add.
https://api.tokenjay.app/peers/list?unreachable=false&limit=50

**Comment by Eeysirhc** [comment]
@cafebedouin i think it might be this one: http://ergonodes.net/list

**Comment by cafebedouin** [comment]
I'll add both. I thought you were taking the weekend off?

**Comment by Eeysirhc** [comment]
https://github.com/Eeysirhc/sigmabot/pull/57/commits/ba8a8ecd51293f05a1b276e4ea3608876aa17ac6

**Comment by Eeysirhc** [comment]
thank you @cafebedouin !
