### ISSUE TITLE
Consider suppressing URL unfurling for bot output

### ISSUE THREAD

**Issue by mattsbennett** [Eeysirhc/sigmabot#41]
I don't have bot experience with Discord (a bit with Slack), so not sure if "unfurling" is the Discord lingo, or if this is possible with Discord, but for example, from running `.cex`:

<img width="644" alt="Screen Shot 2022-09-16 at 3 49 50 PM" src="https://user-images.githubusercontent.com/2965457/190827688-2826b6cb-c4d2-4d3a-b7df-71545684d9cc.png">

All the unfurled info after the main output is subject to the title/description attributes at the referenced URLs, and for many pages it's keyword-stuffed SEO bait, or just not readable or useful at all. I'm wondering if it would be better to just suppress unfurling for bot messages (if indeed that's possible with Discord).

**Comment by Eeysirhc** [comment]
Great idea - suppressed the link embeds. Thanks! :) 

https://github.com/Eeysirhc/sigmabot/commit/93ea16fbae0f9155572bcd8b9c753cfdba672168

**Comment by mattsbennett** [comment]
Awesome 🙌
