### ISSUE TITLE
update .wen binance

### ISSUE THREAD

**Issue by cafebedouin** [Eeysirhc/sigmabot#63]
With this text: While Binance is, in fact, the largest exchange in the world, Ergo is only a few years old and step by step has been achieving all its goals, so eventually, sooner or later, they will inevitably list Ergo.

**Comment by Eeysirhc** [comment]
https://github.com/Eeysirhc/sigmabot/commit/ac1dd6306dab47fe8a84ef0eff5e30730be5e091
