### ISSUE TITLE
.bridge

### ISSUE THREAD

**Issue by cafebedouin** [Eeysirhc/sigmabot#64]
In cryptocurrencies, bridges move assets from one cryptocurrency blockchain to another. The two most frequently discussed on Ergo are Rosen Bridge and AnetaBTC.

Rosen Bridge video
https://www.youtube.com/watch?v=Xsiy-yPJQ6w

Rosen Bridge compared to Interlay bridges.
https://medium.com/@anetaBTC/rosen-bridge-vs-interlay-an-analysis-on-wrapping-bitcoin-c9ae84da0e9d

**Comment by Eeysirhc** [comment]
https://github.com/Eeysirhc/sigmabot/commit/2411e73f833383003fec165585d9ba2c7f617957
